# Generated by Django 5.1.1 on 2024-11-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutribalance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$BMkKD15vzlaBAW5SgawFsL$PIv1RvlkP4Z1+JFLq0sl6xXEv2Z02m1rTthU/0C41Go=', max_length=128),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
