# Generated by Django 5.1.1 on 2024-11-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutribalance', '0002_paciente_password_alter_paciente_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='historial_medico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
