# Generated by Django 5.1.1 on 2024-11-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutribalance', '0003_remove_paciente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')], max_length=10, null=True),
        ),
    ]
