# Generated by Django 5.1.1 on 2024-11-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutribalance', '0004_paciente_altura_paciente_edad_paciente_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='fotos_perfil/default.jpg', upload_to='fotos_perfil/'),
        ),
    ]
