# Generated by Django 5.1.1 on 2024-11-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutribalance', '0005_paciente_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
