# Generated by Django 5.1.1 on 2024-11-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutribalance', '0008_profesional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profesional',
        ),
        migrations.AddField(
            model_name='paciente',
            name='es_profesional',
            field=models.BooleanField(default=False),
        ),
    ]
